# Generated by Django 3.1 on 2024-03-13 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20240306_1623'),
        ('category', '0002_auto_20240306_1207'),
    ]

    operations = [
    ]
